### ISSUE TITLE
Build failures:

### ISSUE THREAD

**Issue by phadej** [GregorySchwartz/blosum#1]
See http://matrix.hackage.haskell.org/package/blosum
### GHC-7.8:

```
src/Types.hs:47:10:
    Not in scope: type constructor or class ‘Monoid’
    Perhaps you meant ‘Monad’ (imported from Prelude)
```
### GHC-7.10

```
Configuring blosum-0.1.1.1...
Dependency base ==4.8.2.0: using base-4.8.2.0
Dependency blosum -any: using blosum-0.1.1.1
Dependency containers ==0.5.6.2: using containers-0.5.6.2
Dependency fasta ==0.10.2.0: using fasta-0.10.2.0
Dependency lens ==4.14: using lens-4.14
Dependency optparse-applicative ==0.12.1.0: using
optparse-applicative-0.12.1.0
Dependency pipes ==4.1.9: using pipes-4.1.9
Dependency pipes-text ==0.0.2.1: using pipes-text-0.0.2.1
Dependency split ==0.2.3.1: using split-0.2.3.1
Dependency text ==1.2.2.1: using text-1.2.2.1
Dependency text-show ==3.2.2: using text-show-3.2.2
```

```
src/Types.hs:33:60:
    Ambiguous occurrence ‘AA’
    It could refer to either ‘Types.AA’, defined at src/Types.hs:18:1
                          or ‘Data.Fasta.Text.AA’,
```
### GHC-8.0

Fails to find a build-plan. I'm not sure where the problem is, as [`fasta matrix.h.h.o`](http://matrix.hackage.haskell.org/package/fasta) seems to read backjump limit too on GHC-8.0.

_EDIT_ this might explain: http://matrix.hackage.haskell.org/package/pipes-text

**Comment by GregorySchwartz** [comment]
I fixed the issue with the ambiguous occurrences but unfortunately the dependencies need to be upgraded to GHC 8.0 before my programs can work, so I'll leave this issue open if building on GHC 8.0.

**Comment by hvr** [comment]
@GregorySchwartz  I just noticed that the last version of this package is still broken on GHC 7.10 and 7.8:

```
Configuring component lib from blosum-0.1.1.3
Preprocessing library blosum-0.1.1.3...
[1 of 5] Compiling Types            ( src/Types.hs, /tmp/matrix-worker/1480537057/dist-newstyle/build/x86_64-linux/ghc-7.10.3/blosum-0.1.1.3/build/Types.o )
[2 of 5] Compiling Utility          ( src/Utility.hs, /tmp/matrix-worker/1480537057/dist-newstyle/build/x86_64-linux/ghc-7.10.3/blosum-0.1.1.3/build/Utility.o )
[3 of 5] Compiling Cluster          ( src/Cluster.hs, /tmp/matrix-worker/1480537057/dist-newstyle/build/x86_64-linux/ghc-7.10.3/blosum-0.1.1.3/build/Cluster.o )
[4 of 5] Compiling Matrix           ( src/Matrix.hs, /tmp/matrix-worker/1480537057/dist-newstyle/build/x86_64-linux/ghc-7.10.3/blosum-0.1.1.3/build/Matrix.o )
[5 of 5] Compiling Print            ( src/Print.hs, /tmp/matrix-worker/1480537057/dist-newstyle/build/x86_64-linux/ghc-7.10.3/blosum-0.1.1.3/build/Print.o )

Configuring component exe:blosum from blosum-0.1.1.3
Warning: The package has a version range for a dependency on an internal library: blosum -any && ==0.1.1.3. This version range has no semantic meaning and can be removed.
Preprocessing executable 'blosum' for blosum-0.1.1.3...

app/Main.hs:14:8:
    Could not find module ‘Data.Semigroup’
    It is a member of the hidden package ‘semigroups-0.18.2@BXwYYtsEMWZJSjSVzaBK2L’.
    Perhaps you need to add ‘semigroups’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘semigroups-0.16.2.2@216D4NMe2XmD1D7na6rEFK’.
    Perhaps you need to add ‘semigroups’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘semigroups-0.17.0.1@IJjooeZsBV9213xrhdqNnA’.
    Perhaps you need to add ‘semigroups’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘semigroups-0.18.2@HeLXC50ICe5E60uwTshObg’.
    Perhaps you need to add ‘semigroups’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

```
Configuring component lib from blosum-0.1.1.3
Preprocessing library blosum-0.1.1.3...
[1 of 5] Compiling Types            ( src/Types.hs, /tmp/matrix-worker/1480537466/dist-newstyle/build/x86_64-linux/ghc-7.8.4/blosum-0.1.1.3/build/Types.o )

src/Types.hs:47:10:
    Not in scope: type constructor or class ‘Monoid’
    Perhaps you meant ‘Monad’ (imported from Prelude)
cabal: Failed to build blosum-0.1.1.3 (which is required by exe:blosum from
blosum-0.1.1.3).
```

Moreover, the `description` ("Please see README.md") is not a proper description for your package (and Hackage will show a link to the README at the end of the description *if* a README is found inside the source tar-ball; therefore that phrase is redundant), and hence this will cause poor experience for users (NB: your package won't be properly indexed by Hackage's package search feature and thus hurt its discoverability). See also [this posting](https://mail.haskell.org/pipermail/haskell-cafe/2016-November/125541.html) for more details.

**Comment by GregorySchwartz** [comment]
Thanks for the notification. Semigroups added, appropriate description added. The semigroups and monoid issues are a bit "out of date" in my eyes--so I'm now requiring base >= 4.9 to fully convert to GHC 8.
